name: vanish-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - nextflow>=26.0
  - fastp>=0.23.2
  - bowtie2>=2.5.1
  - samtools>=1.17
  - seqkit>=2.4.0
  - python>=3.10
  - pip
  - wget
  - pip:
    - .
    